import Link from 'next/link'
import Image from 'next/image'
import { Footer } from '../../components/legal-site'
import KarachiShortCta from '../../components/karachi-short-cta'
import { firm } from '../../lib/legal-data'

export const metadata = {
  title: 'Property Lawyers In Pakistan | Title And Disputes',
  description: 'Property lawyers in Pakistan for title review, sale deeds, inheritance, partition and possession disputes. Consult Right Law Associates in Karachi or Islamabad.',
  alternates: { canonical: 'https://rightlaw.pk/property-law-in-pakistan/' },
}

const sections = [
  ['Property Lawyers In Pakistan For Title And Ownership', 'Review The Complete Chain Of Property Documents', 'Property law in Pakistan involves ownership, possession, transfer, inheritance and the remedies available when those rights are disputed. A useful legal assessment starts with the actual documents and the client’s objective: buying a home, protecting an inherited share, recovering possession or challenging a defective transfer. Right Law Associates reviews these issues before recommending a transaction or court proceeding. The property’s location, tenure, relevant authority and previous dealings all influence the next step. A flat in a housing project may require different checks from agricultural land or a leasehold commercial unit.'],
  ['Property Title Verification Before Purchase', 'Check The Seller’s Authority And Transfer History', 'A buyer should examine the chain of ownership rather than relying on one photocopy, a property agent’s assurance or possession alone. Relevant records may include registered instruments, allotment letters, leases, transfers, revenue entries, authority records and earlier court orders. The seller’s identity and authority must match the records. If an attorney signs, the power of attorney requires separate examination. Mortgages, restrictions, pending litigation and unpaid obligations can affect a proposed purchase. Available records should be compared with the physical property, boundaries and occupancy before substantial payment or an irrevocable commitment.'],
  ['Property Sale Agreements And Registered Transfers', 'Separate Contractual Rights From Ownership', 'An agreement to sell should clearly identify the parties, property, price, payment stages, completion date and obligations concerning possession and documentation. A contract does not automatically complete a transfer of title. The applicable law and tenure determine the instrument, registration and authority approvals needed. Drafting should address default, refund, disputes, existing occupants and outstanding charges. Buyers should preserve payment evidence and avoid informal changes to the agreed terms. Sellers should understand what possession or document handover authorises before allowing it. A lawyer can coordinate the agreement with the intended transfer process.'],
  ['Property Registration, Mutation And Authority Records', 'Understand What Each Property Record Establishes', 'Registration, mutation and an authority’s transfer entry serve different purposes. Registration records an instrument through the legally relevant process; mutation is commonly a revenue-record entry and should not be treated as a complete substitute for title examination. An authority may also require a transfer procedure for property within its jurisdiction. The legal effect of each record depends on the transaction and surrounding evidence. Discrepancies in names, area, survey numbers or ownership history should be investigated before completion. Where original documents are missing, certified records and the reason for the gap require review.'],
  ['Property Inheritance And Protection Of Legal Heirs', 'Identify Every Heir Before Estate Transfer', 'An inherited property dispute requires the deceased owner’s records, death documentation, family information and a complete list of potential heirs. A person occupying the property does not necessarily own every share. The applicable personal law, prior transfers and estate circumstances must be checked before calculating entitlement. Succession or administration documentation may be needed for particular assets, but the appropriate process should be confirmed for the property and jurisdiction. Heirs should obtain advice before signing a relinquishment, family settlement, sale authority or receipt that may affect their rights.'],
  ['Property Partition And Co-Ownership Disputes', 'Assess Division, Settlement And The Correct Forum', 'A co-owner may want a separate share, possession arrangements or a lawful sale and distribution. Counsel should first establish the shares, current use and whether a practical division is possible. Urban buildings and agricultural land can involve different procedures and forums. A negotiated settlement should identify the property precisely and explain possession, expenses and required registration. Where agreement fails, the pleadings should seek the relief that fits the ownership record. All necessary parties must be considered, including heirs or transferees whose interests could be affected by the proposed division.'],
  ['Property Possession And Dispossession Cases', 'Preserve Evidence Before Seeking Relief', 'Possession disputes can involve an owner, tenant, co-owner, licensee or alleged trespasser. The correct remedy depends on the claimant’s legal status and how possession changed. Preserve dated photographs, notices, agreements, utility records, witnesses’ details and previous orders. Civil relief may include recovery of possession or an injunction where legally available. Criminal allegations require an independent assessment of the facts and applicable statute. A complaint should not be assumed to replace a civil title proceeding. Avoid force or self-help eviction that may create further legal exposure or undermine an otherwise valid claim.'],
  ['Property Injunctions And Urgent Court Protection', 'Explain The Threat And Supporting Documents', 'An urgent property matter may involve threatened sale, demolition, construction or interference with possession. Counsel should identify the threatened act, the evidence supporting the right asserted and the court able to grant relief. Interim protection is discretionary and depends on the applicable legal tests and circumstances. An injunction application should be coordinated with the main relief rather than drafted as an isolated request. Clients should disclose previous proceedings and orders at the outset. Delay, incomplete disclosure or a mistaken description of the property can materially affect the court’s assessment.'],
  ['Property Fraud, Forged Documents And Cancellation', 'Compare Official Records With The Challenged Instrument', 'A disputed signature, fabricated authority letter or unauthorised transfer requires careful evidence preservation. Obtain reliable copies of the challenged instrument and compare registration or authority records with the client’s originals. Counsel may need to consider declaration, cancellation, possession, injunction or another remedy according to the facts. Alleged forgery may also justify a separate criminal-law assessment, but allegations should be supported by specific material. Limitation and necessary parties require early attention. Keep a chronology of discovery, notices, payments and communications so that the legal strategy addresses the entire transaction.'],
  ['Property Lawyers In Karachi For Local Transactions', 'Check The Relevant Land And Housing Authority', 'Karachi property work may involve revenue land, cooperative societies, development authorities, cantonment jurisdictions or other housing arrangements. A single checklist cannot establish title across every tenure. Right Law Associates coordinates document review through its DHA and Gulistan-e-Jauhar branches and identifies the authority whose record must be examined. The assessment should address approvals, lease conditions, transfer restrictions, occupancy and the seller’s documents. This national property-law page explains the broader framework; an individual Karachi transaction still needs review against its particular record and the current requirements of the relevant authority.'],
  ['Property Law Support For Overseas Pakistanis', 'Use A Purpose-Specific Attorney Or Proxy', 'An overseas owner can often begin with scanned documents and a remote consultation. A power of attorney should specify the actions actually required, such as litigation, collection of certified records or a defined transfer. Authentication, registration and acceptance requirements must be checked before execution. Broad authority should not be signed without understanding its effect. Preserve copies and agree how the representative will report progress and handle originals. Personal attendance may still be required by a court or authority. The procedure should be planned around the country of execution and the Pakistani property concerned.'],
]

const faqs = [
  ['What Do Property Lawyers In Pakistan Handle?', 'They advise on title verification, transfer documentation, inheritance, co-ownership, partition, possession, tenancy and property litigation. The appropriate lawyer and forum depend on the property record and relief required.'],
  ['Does An Agreement To Sell Transfer Ownership?', 'A contract for sale should be distinguished from the completed transfer. The necessary conveyance, registration and authority process depend on the transaction and tenure. Obtain advice before treating an agreement as proof of completed ownership.'],
  ['Is Mutation Alone Enough To Prove Title?', 'A mutation entry should be examined with the underlying transaction and other evidence. It is not a substitute for reviewing the ownership chain, relevant instruments and competing claims.'],
  ['What Documents Are Needed For Property Review?', 'Send identity documents, ownership instruments, leases or allotments, transfer records, agreements, payment evidence and existing notices or court orders. Include the address, property identifiers and a short chronology.'],
  ['Can An Overseas Pakistani Start Remotely?', 'Yes, initial assessment can often use electronic records. Later steps may require authenticated authority, original documents or attendance, depending on the court, registration office and property authority.'],
  ['Can A Co-Owner Sell The Entire Property?', 'The seller’s legal interest and authority must be established. A co-owner should not be assumed to have authority to transfer everyone’s interests merely because that person holds documents or occupies the property.'],
  ['How Is Inherited Property Divided?', 'Counsel identifies the heirs, applicable personal law, estate assets and relevant documents before assessing shares and the transfer or partition route. Previous transfers and disputed ownership must also be considered.'],
  ['Can Women Claim Their Inherited Property Rights?', 'An heir’s entitlement should be assessed under the applicable law. Women should obtain independent advice before signing releases, settlements or sale documents and preserve evidence of any disputed exclusion from the estate.'],
  ['Which Court Hears A Property Dispute?', 'Jurisdiction depends on location, subject matter, valuation, tenure and relief. Some disputes involve civil courts, while revenue, tenancy or authority-specific matters may require another forum.'],
  ['Can An Injunction Stop A Threatened Transfer?', 'Interim protection may be available where the legal requirements are met. Counsel must evaluate the threatened action, title or other right asserted, supporting evidence and the appropriate main claim.'],
  ['What If Someone Occupies My Property?', 'Clarify whether the occupier is a tenant, co-owner, licensee or alleged trespasser. The status and possession history determine the route. Preserve records and seek advice before attempting removal.'],
  ['Is A Police Complaint Enough For A Title Dispute?', 'Civil ownership and possession claims may still require civil proceedings. Possible criminal conduct should be separately assessed against the facts and law; a complaint does not automatically determine title.'],
  ['What If The Seller Uses A Power Of Attorney?', 'Check the attorney’s identity, document authenticity, scope, continued validity and required authentication or registration. Confirm that it authorises the proposed action and is acceptable to the relevant authority.'],
  ['Should I Pay Before Title Verification?', 'Review the ownership and agreed transaction terms before substantial payment. A payment arrangement should record conditions, deadlines and consequences of non-completion rather than relying only on verbal assurances.'],
  ['Can A Forged Property Transfer Be Challenged?', 'Potential remedies require examination of the instrument, records, signature evidence, necessary parties and limitation. Preserve official copies and correspondence, and obtain advice on civil relief and any criminal allegations.'],
  ['Are Karachi Property Procedures Uniform?', 'No. Requirements can differ between revenue land, leasehold property, societies, development authorities and cantonment jurisdictions. Determine the tenure and relevant authority before relying on a generic transfer checklist.'],
  ['Can A Property Dispute Be Settled?', 'A lawful negotiated settlement may be possible. It should identify each party’s rights, possession, consideration and the documents or registration required for implementation, including any court approval where applicable.'],
  ['How Long Does Property Litigation Take?', 'Timing depends on service, contested issues, evidence, interim proceedings, court workload and possible appeals. A responsible estimate requires reviewing the file; a fixed outcome or completion date cannot be assumed.'],
  ['How Are Property Legal Fees Agreed?', 'Fees depend on document volume, transaction value and complexity, drafting, filing and representation required. Confirm the agreed scope and expenses before work begins.'],
  ['How Do I Contact Right Law Associates?', 'Call or WhatsApp +92 333 1127830 with the property location, a concise description and available documents. Offices are in Islamabad, Karachi DHA, Karachi Gulistan-e-Jauhar and Lahore.'],
]

export default function PropertyLawPage() {
  const url = 'https://rightlaw.pk/property-law-in-pakistan/'
  const schema = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'LegalService', '@id': `${url}#service`, name: 'Property Law Services In Pakistan', url, telephone: firm.phone, areaServed: 'Pakistan', provider: { '@type': 'Organization', name: firm.legalName, url: 'https://rightlaw.pk/' } },
    { '@type': 'FAQPage', mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) },
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://rightlaw.pk/' }, { '@type': 'ListItem', position: 2, name: 'Property Law', item: url }] },
  ] }
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <main className="property-law-page family-law-page">
      <section className="hero"><div className="container property-hero">
        <p className="eyebrow gold">Property Law • Pakistan</p>
        <h1>Property Lawyers In Pakistan For Title, Transfers And Disputes</h1>
        <p className="hero-lede">Right Law Associates helps owners, buyers and legal heirs assess property records, protect their interests and choose the correct transaction or litigation route.</p>
        <p className="property-office-line">Islamabad Head Office · Karachi DHA And Gulistan-e-Jauhar · Lahore</p>
        <div className="hero-actions"><Link href="/contact/" className="button button-gold">Consult A Property Lawyer</Link><a href={`tel:${firm.phone}`} className="button button-outline-light">Call {firm.phone}</a><a href={`https://wa.me/${firm.whatsapp}`} className="text-link light-link">WhatsApp</a></div>
      </div></section>
      <KarachiShortCta />
      <article className="section family-article"><div className="container family-article-inner">
        <h2>Property Law Advice From Experienced Counsel</h2>
        <h3>Syed M. Akhtar Rizvi — Advocate Supreme Court Of Pakistan</h3>
        <div className="senior-counsel-card"><Image unoptimized width={92} height={108} className="senior-counsel-photo" src="/images/syed-akhtar-rizvi.webp" alt="Syed M. Akhtar Rizvi, Advocate Supreme Court of Pakistan" /><div><p>Senior trial and appellate counsel with more than four decades of legal practice, including complex property litigation, High Court appeals and Supreme Court proceedings where maintainable.</p><p className="senior-counsel-note">Property matters are assessed with the relevant Right Law Associates practice team. The required forum and counsel depend on the individual case.</p></div></div>
        <Image className="property-content-image" src="/images/legal-consultation.png" width={1000} height={600} sizes="(max-width: 800px) 100vw, 940px" priority alt="Property document consultation at Right Law Associates" />
        {sections.map(([title, subtitle, copy]) => <section key={title}><h2>{title}</h2><h3>{subtitle}</h3><p>{copy}</p></section>)}
        <h2>Property Documents And The Questions They Answer</h2>
        <div className="property-table-wrap"><table><thead><tr><th>Record</th><th>Review Purpose</th><th>Further Check</th></tr></thead><tbody>
          <tr><td>Registered Instrument</td><td>Nature Of The Recorded Transfer</td><td>Earlier Title, Authority And Restrictions</td></tr>
          <tr><td>Allotment Or Lease</td><td>Tenure And Conditions</td><td>Transfer Approval And Outstanding Obligations</td></tr>
          <tr><td>Mutation Or Revenue Entry</td><td>Recorded Revenue Position</td><td>Underlying Transaction And Competing Claims</td></tr>
          <tr><td>Power Of Attorney</td><td>Representative’s Authority</td><td>Validity, Scope And Authentication</td></tr>
        </tbody></table></div>
        <h2>Related Property Law And Inheritance Guides</h2>
        <ul><li><Link href="/property-disputes/">Property Disputes</Link></li><li><Link href="/rental-and-tenancy-law-of-pakistan/">Rental And Tenancy Law</Link></li><li><Link href="/succession-certificate-letter-of-administration/">Succession Certificates And Letters Of Administration</Link></li><li><Link href="/civil-law/">Civil Law And Litigation</Link></li></ul>
        <h2>Property Law Sources And Further Legal Information</h2>
        <h3>Check Applicable Law And The Property’s Jurisdiction</h3>
        <p>The <a href="https://pakistancode.gov.pk/pdffiles/administrator77923ce792b475e339e1f46ba0442da3.pdf">Transfer Of Property Act, 1882</a> and <a href="https://pakistancode.gov.pk/pdffiles/administrator0f29bc9f1e3dfed37c0034eed1e29d53.pdf">Registration Act, 1908</a> are relevant starting points for transfer and registration questions. Applicable provincial amendments, tenure and authority rules must also be examined. Related legal information is available through <a href="https://qanoonhouse.com/">Qanoon House</a> and <a href="https://karachilawyers.com.pk/">Karachi Lawyers</a>.</p>
        <h2>Frequently Asked Questions About Property Law</h2>
        <div className="faq-list">{faqs.map(([question, answer]) => <section className="faq-item active" key={question}><h3>{question}</h3><p>{answer}</p></section>)}</div>
        <h2>Discuss Your Property Matter With Right Law Associates</h2>
        <h3>Send The Property Location, Chronology And Documents</h3>
        <p>Start with the records you hold and explain the outcome you need. Our team can identify missing documents, the relevant authority and a practical next step. This page provides general information; advice on a transaction or dispute requires assessment of the actual record.</p>
        <div className="hero-actions"><Link href="/contact/" className="button button-gold">Request Property Advice</Link><a href={`tel:${firm.phone}`} className="button button-dark">Call {firm.phone}</a></div>
      </div></article>
    </main><Footer />
  </>
}
