'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, BriefcaseBusiness, Building2, ChevronDown, Gavel, HeartHandshake, Menu, MessageCircle, Phone, Scale, ShieldCheck, X } from 'lucide-react'
import { articles, cities, faqs, firm, practiceAreas, practicePath, cityPath } from '../lib/legal-data'

const icons = { family: HeartHandshake, scale: Scale, heart: HeartHandshake, building: Building2, briefcase: BriefcaseBusiness, gavel: Gavel }

function Logo() {
  return <Link href="/" className="logo" aria-label="Right Law Associates home"><span className="logo-mark"><span>R</span></span><span><strong>RIGHT LAW</strong><small>ASSOCIATES</small></span></Link>
}

function Header() {
  const [open, setOpen] = useState(false)
  const [openDropdown, setOpenDropdown] = useState(null)
  const closeAll = () => { setOpen(false); setOpenDropdown(null) }
  return <header className="site-header"><div className="topbar"><div className="container topbar-inner"><span>Professional legal representation across Pakistan</span><span className="top-contact"><a href={`tel:${firm.phone}`}>Call {firm.phone}</a></span></div></div><div className="container nav-wrap"><Logo /><button className="mobile-menu" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button><nav className={open ? 'main-nav is-open' : 'main-nav'}><Link href="/about-us/" onClick={closeAll}>About Us</Link><div className="nav-dropdown"><button onClick={() => setOpenDropdown(openDropdown === 'practice' ? null : 'practice')} aria-expanded={openDropdown === 'practice'}>Practice Areas <ChevronDown size={14} /></button>{openDropdown === 'practice' && <div className="dropdown-menu">{practiceAreas.map((item) => <Link href={practicePath(item.slug)} key={item.slug} onClick={closeAll}>{item.name}<ArrowUpRight size={14} /></Link>)}</div>}</div><Link href="/meet-our-attorneys/" onClick={closeAll}>Lawyers</Link><div className="nav-dropdown"><button onClick={() => setOpenDropdown(openDropdown === 'locations' ? null : 'locations')} aria-expanded={openDropdown === 'locations'}>Locations <ChevronDown size={14} /></button>{openDropdown === 'locations' && <div className="dropdown-menu">{cities.map((city) => <Link href={cityPath(city.name)} key={city.name} onClick={closeAll}>{city.name}<ArrowUpRight size={14} /></Link>)}</div>}</div><Link href="/blog/" onClick={closeAll}>Blog</Link><Link href="/contact/" className="nav-cta" onClick={closeAll}>Contact Us <ArrowUpRight size={15} /></Link></nav></div></header>
}

function SectionIntro({ eyebrow, title, copy, light = false }) { return <div className={`section-intro ${light ? 'light' : ''}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div> }

function Hero() { return <section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow gold">RIGHT LAW ASSOCIATES</p><h1>Family, Property, Tax &amp; Corporate Lawyers in Karachi, Islamabad &amp; Lahore</h1><p className="hero-lede">With over 40 years of legal practice, Right Law Associates stands among the most trusted family lawyers, property lawyers, and business lawyers in Pakistan, associated with Qanoon Group and a member of the Pakistan Legal Forum, delivering structured legal services across Pakistan with offices in Karachi, Lahore, Islamabad and Rawalpindi.</p><div className="hero-actions"><Link className="button button-gold" href="/contact/">Consult a Lawyer <ArrowUpRight size={17} /></Link><a className="button button-outline-light" href={`tel:${firm.phone}`}><Phone size={16} /> Call Now</a><a className="text-link light-link" href={`https://wa.me/${firm.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={17} /> WhatsApp Us</a></div><div className="hero-proof"><div><strong>Since 1985</strong><span>Legal practice</span></div><div><strong>Pakistan-wide</strong><span>Coordinated assistance</span></div><div><strong>Confidential</strong><span>Professional handling</span></div></div></div><div className="hero-visual"><img src="/images/legal-consultation.png" alt="Lawyer consulting with clients in a professional office" /><div className="hero-caption"><span className="caption-line" /><span>Guidance when it counts</span></div></div></div><div className="hero-bottom"><div className="container hero-bottom-inner"><span>Family</span><span>Corporate</span><span>Property</span><span>Civil & Criminal</span><span>Taxation</span><span>Succession</span></div></div></section> }

function AuthorityIntro() { return <section className="section" style={{background:'#fff'}}><div className="container" style={{maxWidth:980}}><p className="eyebrow">Legal services in Pakistan</p><h2 style={{fontFamily:'Georgia,serif',fontSize:'clamp(34px,4vw,50px)',lineHeight:1.1,color:'#173b35',margin:'0 0 20px'}}><b>Legal Advice and Representation Across Major Areas of Pakistani Law</b></h2><p className="section-copy" style={{maxWidth:'none'}}>Right Law Associates advises individuals, families, businesses and overseas Pakistanis on legal matters that may involve courts, government authorities, registrations, contracts, personal status or property rights. Our work includes <Link href="/family-law-in-pakistan/">family law in Pakistan</Link>, <Link href="/divorce-law/">divorce and khula</Link>, <Link href="/child-custody/">child custody</Link>, <Link href="/property-law-in-pakistan/">property law</Link>, <Link href="/civil-law/">civil litigation</Link>, <Link href="/corporate-tax-law-services/">corporate and tax matters</Link>, <Link href="/intellectual-property-in-pakistan/">intellectual property</Link> and <Link href="/succession-certificate-in-pakistan-for-legal-heirs/">succession proceedings</Link>.</p><p className="section-copy" style={{maxWidth:'none'}}>Many legal problems overlap. A family dispute may also involve maintenance, guardianship or property. A succession matter may require examination of title documents, death records and the status of legal heirs. A business issue may involve registration, taxation and contractual liability. For that reason, our approach begins with identifying the correct legal issue and forum before any notice, petition or application is prepared.</p><p className="section-copy" style={{maxWidth:'none'}}>Clients can use the detailed practice pages and our <Link href="/blog/">Pakistani legal blog</Link> to understand the general framework before requesting case-specific advice. Where documents, dates, notices or previous court orders materially affect the legal position, those records should be reviewed before action is taken.</p></div></section> }

function Services() { return <section className="section services" id="services"><div className="container"><SectionIntro eyebrow="What we do" title="Legal services organised around the matter you need to solve" copy="From sensitive family disputes to property, corporate, taxation and litigation matters, our lawyers help clients understand their legal position and the next lawful step." /><div className="service-grid">{practiceAreas.map((item, i) => { const Icon = icons[item.icon]; return <Link href={practicePath(item.slug)} className="service-card" key={item.slug}><span className="card-number">{String(i + 1).padStart(2, '0')}</span><span className="service-icon"><Icon size={22} strokeWidth={1.5} /></span><h3>{item.name}</h3><p>{item.description}</p><span className="text-link">Explore service <ArrowUpRight size={15} /></span></Link> })}</div></div></section> }

function SplitFeature({ eyebrow, title, copy, items, image, alt, reverse = false, href = '/contact/' }) { return <section className={`split-feature ${reverse ? 'reverse' : ''}`}><div className="split-image"><img src={image} alt={alt} /></div><div className="split-content"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="section-copy">{copy}</p><ul className="check-list">{items.map(item => <li key={item}><span><ShieldCheck size={16} /></span>{item}</li>)}</ul><Link href={href} className="text-link">Discuss your matter <ArrowUpRight size={15} /></Link></div></section> }

function PracticeLinks() { return <section className="section" style={{background:'#f7f3eb'}}><div className="container"><SectionIntro eyebrow="Explore the law" title="Detailed legal pages for common matters" copy="Use these connected pages to move directly to the part of Pakistani law that matches your situation." /><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:16,marginTop:42}}><div className="service-card"><h3>Family and Matrimonial Law</h3><p>Read about <Link href="/family-law-in-pakistan/">family law</Link>, <Link href="/divorce-law/">divorce law</Link>, <Link href="/dissolution-of-marriage-in-pakistan/">dissolution of marriage</Link>, <Link href="/child-custody/">child custody</Link>, <Link href="/legal-guardianship-laws-of-pakistan/">guardianship</Link> and <Link href="/maintenance-in-pakistan/">maintenance</Link>.</p></div><div className="service-card"><h3>Marriage and Registration</h3><p>See the guides on <Link href="/court-marriage-procedure-in-pakistan/">court marriage procedure</Link>, <Link href="/online-marriage/">online marriage</Link>, <Link href="/nikah-nama/">Nikah Nama</Link>, <Link href="/marriage-registration-certificate/">marriage certificates</Link> and <Link href="/divorce-registration-certificate/">divorce certificates</Link>.</p></div><div className="service-card"><h3>Property and Succession</h3><p>Start with <Link href="/property-law-in-pakistan/">property law in Pakistan</Link>, then review <Link href="/property-disputes/">property disputes</Link>, <Link href="/rental-and-tenancy-law-of-pakistan/">rental and tenancy law</Link> or <Link href="/succession-certificate-letter-of-administration/">succession and letters of administration</Link>.</p></div><div className="service-card"><h3>Civil, Corporate and Tax</h3><p>Read about <Link href="/civil-law/">civil law</Link>, <Link href="/lawyers-for-litigation-in-the-court/">court litigation</Link>, <Link href="/corporate-tax-law-services/">corporate and tax law</Link>, <Link href="/fbr-income-tax-return-filing-lawyers-pakistan/">income tax return filing</Link> and <Link href="/ntn-verification-from-the-fbr-in-pakistan/">NTN verification</Link>.</p></div></div></div></section> }

function About() { return <section className="section about" id="about"><div className="container"><div className="about-grid"><div><SectionIntro eyebrow="A considered approach" title="Legal advice built around facts, procedure and practical next steps" copy="Right Law Associates represents clients across Pakistan in matters where careful drafting, correct jurisdiction and timely legal action can materially affect the outcome. Our practice combines litigation, advisory work and documentation across several specialist teams." /><Link href="/about-us/" className="text-link">About Right Law Associates <ArrowUpRight size={15} /></Link></div><div className="about-note"><span className="quote-mark">“</span><p>Good legal advice does more than explain the law. It helps a client understand the available options, evidence and procedure before taking the next step.</p><span className="note-rule" /><small>Right Law Associates</small></div></div></div></section> }

function Team() { return <section className="section team" id="team"><div className="container"><SectionIntro eyebrow="People behind the practice" title="Senior supervision with specialist legal teams" copy="Right Law Associates coordinates matters through lawyers working in family, property, corporate, taxation, civil and criminal law across Pakistan." /><div className="team-grid"><div className="lawyer-card"><div className="lawyer-image"><img src="/images/legal-consultation.png" alt="Right Law Associates legal consultation" /></div><div><p className="eyebrow">Legal team</p><h3>Right Law Associates</h3><p>Multi-practice legal representation and advisory work</p><Link href="/meet-our-attorneys/" className="text-link">Meet our attorneys <ArrowUpRight size={15} /></Link></div></div><div className="team-statement"><span className="statement-icon"><Scale size={24} /></span><h3>Professionalism in every brief.</h3><p>We review the facts, identify the appropriate legal route and communicate the next procedural step clearly.</p><Link href="/contact/" className="button button-dark">Start a conversation <ArrowUpRight size={16} /></Link></div></div></div></section> }

function Locations() { return <section className="section locations" id="locations"><div className="container"><div className="locations-header"><SectionIntro eyebrow="Where we work" title="Legal assistance across Pakistan" copy="Right Law Associates coordinates legal work through its principal and regional offices, with consultation arrangements for clients in major cities and overseas." /><Link href="/contact/" className="text-link">Contact the relevant office <ArrowUpRight size={15} /></Link></div><div className="city-grid">{cities.map((city, i) => <Link href={cityPath(city.name)} className="city-card" key={city.name}><span className="city-index">{String(i + 1).padStart(2, '0')}</span><span><strong>Lawyers in {city.name}</strong><small>{city.phone}</small></span><ArrowUpRight size={18} /></Link>)}</div></div></section> }

function Insights() { return <section className="section insights" id="insights"><div className="container"><div className="insights-header"><SectionIntro eyebrow="Legal information" title="Useful context for important legal decisions" copy="Read practical material on Pakistani law, legal procedure and issues that commonly arise before a client files a case or signs a document." /><Link href="/blog/" className="text-link">View all articles <ArrowUpRight size={15} /></Link></div><div className="article-grid">{articles.map(article => <article className="article-card" key={article.slug}><div className="article-meta"><span>{article.category}</span><span>{article.date}</span></div><h3>{article.title}</h3><Link href={article.route} className="text-link">Read article <ArrowUpRight size={15} /></Link></article>)}</div></div></section> }

function FAQ() { const [active, setActive] = useState(0); return <section className="section faq"><div className="container faq-grid"><SectionIntro eyebrow="Questions, answered" title="A little more clarity before you contact a lawyer" copy="These answers are general. The appropriate legal step depends on the facts, documents and jurisdiction involved in your matter." /><div className="faq-list">{faqs.map((faq, i) => <div className={`faq-item ${active === i ? 'active' : ''}`} key={faq.question}><button onClick={() => setActive(active === i ? -1 : i)} aria-expanded={active === i}><span>{faq.question}</span>{active === i ? <X size={17} /> : <ChevronDown size={17} />}</button>{active === i && <p>{faq.answer}</p>}</div>)}</div></div></section> }

function Contact() { return <section className="contact" id="contact"><div className="container contact-grid"><div><p className="eyebrow gold">Discuss your matter</p><h2>Start with the facts.</h2><p>Tell us briefly what legal assistance you require. Our team can direct your inquiry to the appropriate practice area and office.</p><div className="contact-details"><a href={`tel:${firm.phone}`}><Phone size={17} /> {firm.phone}</a><a href={`https://wa.me/${firm.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={17} /> WhatsApp our team</a></div></div><div className="contact-form"><h3>Need a detailed consultation?</h3><p>Use our contact page to share the nature of your matter and the city or jurisdiction involved.</p><Link href="/contact/" className="button button-gold">Request a consultation <ArrowUpRight size={17} /></Link><small>Contacting the firm does not by itself create a lawyer-client relationship.</small></div></div></section> }

function Footer() { return <footer><div className="container footer-grid"><div><Logo /><p className="footer-blurb">Professional legal assistance for individuals, families and businesses across Pakistan.</p></div><div><h4>Practice areas</h4><Link href="/family-law/">Family law</Link><Link href="/property-law-in-pakistan/">Property & inheritance</Link><Link href="/corporate-tax-law-services/">Corporate & tax</Link><Link href="/civil-law/">Civil law</Link></div><div><h4>Locations</h4>{cities.slice(0, 4).map(city => <Link href={cityPath(city.name)} key={city.name}>{city.name}</Link>)}</div><div><h4>Contact</h4><a href={`tel:${firm.phone}`}>{firm.phone}</a><a href={`mailto:${firm.email}`}>{firm.email}</a><span>Pakistan-wide assistance</span></div></div><div className="container footer-bottom"><span>© 2026 Right Law Associates (Pvt) Limited</span><span><Link href="/contact/">Privacy policy</Link><Link href="/contact/">Disclaimer</Link></span></div></footer> }

export default function LegalSite() { return <><Header /><main><Hero /><AuthorityIntro /><About /><Services /><PracticeLinks /><SplitFeature eyebrow="Family law" title="A steady legal strategy for family matters" copy="Family disputes require careful handling because they affect personal status, children, financial rights and future documentation. Our lawyers advise on divorce, khula, custody, guardianship, maintenance and family court proceedings." items={['Divorce, talaq and khula guidance', 'Child custody and guardianship', 'Maintenance, dower and family court matters']} image="/images/legal-consultation.png" alt="Lawyer discussing family legal documents with clients" href="/family-law/" /><SplitFeature reverse eyebrow="Business & tax" title="Legal counsel for companies, businesses and tax matters" copy="From company registration and contracts to taxation and compliance, our corporate and tax practice helps clients understand obligations, manage risk and respond to legal or regulatory issues." items={['Company registration and SECP matters', 'Corporate compliance and advisory', 'Income tax and sales tax guidance']} image="/images/legal-consultation.png" alt="Legal documents on a desk for a business consultation" href="/corporate-tax-law-services/" /><Locations /><Team /><Insights /><FAQ /><Contact /></main><Footer /><a className="mobile-call" href={`tel:${firm.phone}`} aria-label="Call Right Law Associates"><Phone size={18} /></a></> }
