'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, BriefcaseBusiness, Building2, ChevronDown, ChevronRight, Clock3, Gavel, HeartHandshake, Menu, MessageCircle, Phone, Scale, ShieldCheck, X } from 'lucide-react'
import { articles, cities, faqs, firm, practiceAreas, practicePath, cityPath } from '../lib/legal-data'

const icons = { family: HeartHandshake, scale: Scale, heart: HeartHandshake, building: Building2, briefcase: BriefcaseBusiness, gavel: Gavel }

function Logo() {
  return <Link href="#top" className="logo" aria-label="Right Law Associates home"><span className="logo-mark"><span>R</span></span><span><strong>RIGHT LAW</strong><small>ASSOCIATES</small></span></Link>
}

function Header() {
  const [open, setOpen] = useState(false)
  const [practiceOpen, setPracticeOpen] = useState(false)
  return <header className="site-header"><div className="topbar"><div className="container topbar-inner"><span>Professional legal representation across Pakistan</span><span className="top-contact"><a href={`tel:${firm.phone}`}>Call {firm.phone}</a><span className="top-divider" /><span>Available Mon–Sat, 9:00–18:00</span></span></div></div><div className="container nav-wrap"><Logo /><button className="mobile-menu" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button><nav className={open ? 'main-nav is-open' : 'main-nav'}><Link href="#about" onClick={() => setOpen(false)}>About Us</Link><div className="nav-dropdown"><button onClick={() => setPracticeOpen(!practiceOpen)} aria-expanded={practiceOpen}>Practice Areas <ChevronDown size={14} /></button>{practiceOpen && <div className="dropdown-menu">{practiceAreas.map((item) => <Link href={practicePath(item.slug)} key={item.slug} onClick={() => { setPracticeOpen(false); setOpen(false) }}>{item.name}<ArrowUpRight size={14} /></Link>)}</div>}</div><Link href="#team" onClick={() => setOpen(false)}>Lawyers</Link><div className="nav-dropdown"><button onClick={() => setPracticeOpen(!practiceOpen)} aria-expanded={practiceOpen}>Locations <ChevronDown size={14} /></button>{practiceOpen && <div className="dropdown-menu">{cities.map((city) => <Link href={cityPath(city.name)} key={city.name} onClick={() => { setPracticeOpen(false); setOpen(false) }}>{city.name}<ArrowUpRight size={14} /></Link>)}</div>}</div><Link href="#insights" onClick={() => setOpen(false)}>Blog</Link><Link href="#contact" className="nav-cta" onClick={() => setOpen(false)}>Contact Us <ArrowUpRight size={15} /></Link></nav></div></header>
}

function SectionIntro({ eyebrow, title, copy, light = false }) { return <div className={`section-intro ${light ? 'light' : ''}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div> }

function Hero() { return <section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow gold">RIGHT LAW ASSOCIATES (PVT) LIMITED</p><h1>Experienced lawyers for the matters that matter.</h1><p className="hero-lede">Professional legal assistance for individuals, families, businesses and overseas Pakistanis — with sound advice grounded in the realities of Pakistani law.</p><div className="hero-actions"><a className="button button-gold" href="#contact">Consult a Lawyer <ArrowUpRight size={17} /></a><a className="button button-outline-light" href={`tel:${firm.phone}`}><Phone size={16} /> Call Now</a><a className="text-link light-link" href={`https://wa.me/${firm.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={17} /> WhatsApp Us</a></div><div className="hero-proof"><div><strong>Pakistan-wide</strong><span>Legal assistance</span></div><div><strong>Clear advice</strong><span>Practical next steps</span></div><div><strong>Confidential</strong><span>Professional handling</span></div></div></div><div className="hero-visual"><img src="/images/legal-consultation.png" alt="Lawyer consulting with clients in a professional office" /><div className="hero-caption"><span className="caption-line" /><span>Guidance when it counts</span></div></div></div><div className="hero-bottom"><div className="container hero-bottom-inner"><span>Family</span><span>Corporate</span><span>Property</span><span>Civil & Criminal</span><span>Taxation</span><span>Succession</span></div></div></section> }

function Services() { return <section className="section services" id="services"><div className="container"><SectionIntro eyebrow="What we do" title="Legal services with a clear point of view" copy="From urgent family matters to long-term corporate counsel, our lawyers help you understand your position and act with purpose." /><div className="service-grid">{practiceAreas.map((item, i) => { const Icon = icons[item.icon]; return <Link href={practicePath(item.slug)} className="service-card" key={item.slug}><span className="card-number">0{i + 1}</span><span className="service-icon"><Icon size={22} strokeWidth={1.5} /></span><h3>{item.name}</h3><p>{item.description}</p><span className="text-link">Explore service <ArrowUpRight size={15} /></span></Link> })}</div></div></section> }

function SplitFeature({ eyebrow, title, copy, items, image, alt, reverse = false }) { return <section className={`split-feature ${reverse ? 'reverse' : ''}`}><div className="split-image"><img src={image} alt={alt} /></div><div className="split-content"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="section-copy">{copy}</p><ul className="check-list">{items.map(item => <li key={item}><span><ShieldCheck size={16} /></span>{item}</li>)}</ul><a href="#contact" className="text-link">Discuss your matter <ArrowUpRight size={15} /></a></div></section> }

function About() { return <section className="section about" id="about"><div className="container"><div className="about-grid"><div><SectionIntro eyebrow="A considered approach" title="Law that begins with listening" copy="Right Law Associates represents clients across Pakistan in matters where the right advice can change what comes next. We combine legal knowledge with a measured, responsive approach to each matter." /><a href="#contact" className="text-link">Meet our approach <ArrowUpRight size={15} /></a></div><div className="about-note"><span className="quote-mark">“</span><p>Good legal advice does more than explain the law. It helps you make a sound decision with the facts in front of you.</p><span className="note-rule" /><small>Right Law Associates</small></div></div></div></section> }

function Team() { return <section className="section team" id="team"><div className="container"><SectionIntro eyebrow="People behind the practice" title="A team prepared to help" copy="Our growing legal team brings focused experience to the issues individuals, families and businesses face every day." /><div className="team-grid"><div className="lawyer-card"><div className="lawyer-image"><img src="/images/legal-consultation.png" alt="Right Law Associates legal professional" /></div><div><p className="eyebrow">Principal Associate</p><h3>Right Law Legal Team</h3><p>Family, property and corporate matters</p><a href="#contact" className="text-link">View profile <ArrowUpRight size={15} /></a></div></div><div className="team-statement"><span className="statement-icon"><Scale size={24} /></span><h3>Professionalism in every brief.</h3><p>We take time to understand the circumstances, identify the legal options and communicate the next step clearly.</p><a href="#contact" className="button button-dark">Start a conversation <ArrowUpRight size={16} /></a></div></div></div></section> }

function Locations() { return <section className="section locations" id="locations"><div className="container"><div className="locations-header"><SectionIntro eyebrow="Where we work" title="Legal assistance across Pakistan" copy="Our location pages are built around the local legal services and consultation arrangements available in each city." /><a href="#contact" className="text-link">Find your city <ArrowUpRight size={15} /></a></div><div className="city-grid">{cities.map((city, i) => <Link href={cityPath(city.name)} className="city-card" key={city.name}><span className="city-index">0{i + 1}</span><span><strong>Lawyers in {city.name}</strong><small>{city.phone}</small></span><ArrowUpRight size={18} /></Link>)}</div></div></section> }

function Insights() { return <section className="section insights" id="insights"><div className="container"><div className="insights-header"><SectionIntro eyebrow="Legal information" title="Useful context for important decisions" copy="Practical explainers on Pakistani law, process and the questions clients commonly bring to us." /><a href="#contact" className="text-link">View all articles <ArrowUpRight size={15} /></a></div><div className="article-grid">{articles.map(article => <article className="article-card" key={article.slug}><div className="article-meta"><span>{article.category}</span><span>{article.date}</span></div><h3>{article.title}</h3><a href="#contact" className="text-link">Read article <ArrowUpRight size={15} /></a></article>)}</div></div></section> }

function FAQ() { const [active, setActive] = useState(0); return <section className="section faq"><div className="container faq-grid"><SectionIntro eyebrow="Questions, answered" title="A little more clarity" copy="If your question is not listed here, our team can help you understand the best way to proceed." /><div className="faq-list">{faqs.map((faq, i) => <div className={`faq-item ${active === i ? 'active' : ''}`} key={faq.question}><button onClick={() => setActive(active === i ? -1 : i)} aria-expanded={active === i}><span>{faq.question}</span>{active === i ? <X size={17} /> : <ChevronDown size={17} />}</button>{active === i && <p>{faq.answer}</p>}</div>)}</div></div></section> }

function Contact() { return <section className="contact" id="contact"><div className="container contact-grid"><div><p className="eyebrow gold">Let&apos;s discuss your matter</p><h2>Start with a conversation.</h2><p>Tell us briefly what you need help with. We will guide you towards the most appropriate next step.</p><div className="contact-details"><a href={`tel:${firm.phone}`}><Phone size={17} /> {firm.phone}</a><a href={`https://wa.me/${firm.whatsapp}`}><MessageCircle size={17} /> WhatsApp our team</a></div></div><form className="contact-form"><label>Your name<input type="text" placeholder="Your full name" /></label><label>How can we help?<select defaultValue=""><option value="" disabled>Select a legal service</option>{practiceAreas.map(item => <option key={item.slug}>{item.name}</option>)}</select></label><label>Briefly describe your matter<textarea rows="3" placeholder="A few details will help us direct your enquiry"></textarea></label><button type="button" className="button button-gold">Request a consultation <ArrowUpRight size={17} /></button><small>We treat enquiries with discretion. This form does not create a lawyer–client relationship.</small></form></div></section> }

function Footer() { return <footer><div className="container footer-grid"><div><Logo /><p className="footer-blurb">Professional legal assistance for individuals, families and businesses across Pakistan.</p></div><div><h4>Practice areas</h4><Link href="#services">Family law</Link><Link href="#services">Property & inheritance</Link><Link href="#services">Corporate & tax</Link><Link href="#services">Civil & criminal law</Link></div><div><h4>Locations</h4>{cities.slice(0, 4).map(city => <Link href={cityPath(city.name)} key={city.name}>{city.name}</Link>)}</div><div><h4>Contact</h4><a href={`tel:${firm.phone}`}>{firm.phone}</a><a href={`mailto:${firm.email}`}>{firm.email}</a><span>Pakistan-wide assistance</span></div></div><div className="container footer-bottom"><span>© 2026 Right Law Associates (Pvt) Limited</span><span><a href="#contact">Privacy policy</a><a href="#contact">Disclaimer</a></span></div></footer> }

export default function LegalSite() { return <><Header /><main><Hero /><About /><Services /><SplitFeature eyebrow="Family law" title="A steady hand for family matters" copy="Family disputes require legal care and a clear understanding of what is at stake. We advise on divorce, khula, custody, guardianship, maintenance and family court proceedings." items={['Divorce and khula guidance', 'Child custody and guardianship', 'Maintenance and family court matters']} image="/images/legal-consultation.png" alt="Lawyer discussing family legal documents with clients" /><SplitFeature reverse eyebrow="Business & tax" title="Counsel for the work behind the business" copy="Whether you are registering a company, managing compliance or resolving a commercial dispute, our corporate and taxation team helps you make informed decisions." items={['Company registration and SECP matters', 'Corporate compliance and advisory', 'Income tax and sales tax guidance']} image="/images/legal-consultation.png" alt="Legal documents on a desk for a business consultation" /><Locations /><Team /><Insights /><FAQ /><Contact /></main><Footer /><a className="mobile-call" href={`tel:${firm.phone}`} aria-label="Call Right Law Associates"><Phone size={18} /></a></> }
